apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: cpu-intensive-run
  namespace: pipeline-perf
spec:
  pipelineRef:
    name: cpu-intensive-pipeline
  workspaces:
    - name: shared-data
      emptyDir: {}

